### ISSUE TITLE
how to add botstrap 4 to app.js 

### ISSUE THREAD

**Issue by thandonguocmo2020** [vinicius0026/hapi-vue-ssr#1]
please help !
How to add bootstrap 4 to  app.js of vue

**Comment by vinicius0026** [comment]
The app already includes bootstrap via [bootstrap-vue](https://bootstrap-vue.js.org/).

It is loaded in app.js and the plugin is registerd at [line 9](https://github.com/vinicius0026/hapi-vue-ssr/blob/master/app/app.js#L9)
